title: My Docs
description: Documentation for Project X
baseurl: "/justthedocs"        # use "/REPO-NAME" for project sites, or "" for user sites
url: "https://vijaycoderisetechnologies.github.io"
theme: minima      # simple built-in theme (see supported list below)
