title: Servv AI Documentation
description: Documentation site for JustTheDocs
# Because this is a *project site*, baseurl must be your repo name (the subdirectory)
baseurl: "/justthedocs"
url: "https://vijaycoderisetechnologies.github.io"

# --- THEME SETUP ---
remote_theme: "pmarsceill/just-the-docs"

# If you want to use plugins supported by GitHub Pages, include them
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional: markdown, permalinks, etc.
markdown: kramdown
permalink: pretty
