title: Servv AI Support Documentation
description: Learn how to create and manage events with Servv AI on WordPress and Shopify, and explore APIOps for Azure API Management.
baseurl: "/justthedocs"
url: "https://vijaycoderisetechnologies.github.io"
theme: just-the-docs
color_scheme: light

# Enable search
search_enabled: true

# Search button in the header
search_button: true

# Auxiliary links in the header
aux_links:
  "Servv AI":
    - "//servv.ai"
  "APIOps Guide":
    - "//azure.github.io/apiops/"

# Footer content
footer_content: "Built with Jekyll and Just the Docs. &copy; 2025 Vijay Coderise Technologies."

# Enable heading anchors
heading_anchors: true

# Enable last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %d, %Y"


# Navigation
nav_sort: case_insensitive
nav_external_links:
  - title: Servv AI
    url: https://servv.ai
  - title: APIOps Guide
    url: https://azure.github.io/apiops/